name: power_48
description: Application permettant de savoir les 48 lois du pouvoir
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.1.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1

flutter_launcher_icons:
  image_path: assets/images/icon.jpeg
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/lois/
